#!/usr/bin/env bash

CDRCONNECT=jdbc:oracle:thin:@som-racload03:1521/AUTOMTN
CDRUSER=hadoop_mercury
CDRPWD=XU91abLt10aDMb
CDRSPLITBY=FILE_ID

FASTTRACKCONNECT=jdbc:oracle:thin:@som-racload03.humedica.net:1521/AUTOMTN
FASTTRACKUSER=fasttrack
FASTTRACKPWD=Fs9056azePRN1zcwq05
FASTTRACKSPLITBY=FILE_ID


SCHEMA=$1
DEST=RXORDER_TABLES


./acquireRxOrderTable.sh PATREG $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh MEDORDERS $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh PATIENT_FYI_FLAGS $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh ZH_STATE $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh ENCOUNTERVISIT $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh PAT_RACE $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh PATIENT_3 $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh PAT_ENC_HSP $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh HH_PAT_ENC $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh HSP_ACCT_PAT_CSN $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh INPTBILLING_ACCT $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh ZH_CLARITYDRG $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh HSP_ATND_PROV $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh MEDADMINREC $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh ZH_CLARITYDEPT $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh HSP_ACCT_MULT_DRGS $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh ZH_BENEPLAN $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh ZH_MED_UNIT $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh IDENTITY_ID $SCHEMA $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
