package com.humedica.mercury.etl.crossix.memberphi

import com.humedica.mercury.etl.core.engine.EntitySource


class MemberphiMemberphi(config: Map[String,String]) extends EntitySource(config: Map[String,String]) {

    tables = List("member_phi")

    columns = List("ENROLLEE_ID","INDIVIDUAL_ID","FAMILY_ID","SOURCE_MEMBER_ID","FIRST_NAME","MIDDLE_INITIAL","LAST_NAME","PHI_NAME","DATE_OF_BIRTH","GENDER","SSN","MEDICARE_ID",
        "MEDICAID_RECIPIENT_NBR","MEDICAID_FAMILY_NBR","MARITAL_STATUS_CODE","ADDRESS_1","ADDRESS_2","CITY_NAME","STATE_CODE","ZIPCODE","PHONE","DATA_SOURCE","UPDATE_DATE",
        "UPDATE_PROCESS_ID","MEDICAL_CLAIMS_PROCESSOR_CODE","LANGUAGE_CODE","PHI_EFF_DATE","PHI_END_DATE","ADDRESS_TYPE_CODE","MEMBER_PHI_KEY","INDIVIDUAL_ID_MATCH_CODE","ONCE_ASO_IND","LSRD_INDIVIDUAL_ID","LSRD_ENROLLEE_ID","LSRD_MEDICAID_FAMILY_NBR","LSRD_FAMILY_ID","CURR_ADDR_FLG","ALT_ID")

    columnSelect = Map(
        "member_phi" -> List("ENROLLEE_ID","INDIVIDUAL_ID","FAMILY_ID","SOURCE_MEMBER_ID","FIRST_NAME","MIDDLE_INITIAL","LAST_NAME","PHI_NAME","DATE_OF_BIRTH","GENDER","SSN","MEDICARE_ID","MEDICAID_RECIPIENT_NBR","MEDICAID_FAMILY_NBR","MARITAL_STATUS_CODE","ADDRESS_1","ADDRESS_2","CITY_NAME","STATE_CODE","ZIPCODE","PHONE","DATA_SOURCE","UPDATE_DATE","UPDATE_PROCESS_ID","MEDICAL_CLAIMS_PROCESSOR_CODE","LANGUAGE_CODE","PHI_EFF_DATE","PHI_END_DATE","ADDRESS_TYPE_CODE","MEMBER_PHI_KEY","INDIVIDUAL_ID_MATCH_CODE","ONCE_ASO_IND","LSRD_INDIVIDUAL_ID","LSRD_ENROLLEE_ID","LSRD_MEDICAID_FAMILY_NBR","LSRD_FAMILY_ID","CURR_ADDR_FLG","ALT_ID")
    )
}


//build(new MemberphiMemberphi(cfg), allColumns=true).distinct.write.parquet(cfg.get("EMR_DATA_ROOT").get+"/MEMBER_PHI_201711")