#!/usr/bin/env bash

CDRCONNECT=jdbc:oracle:thin:@som-racload03:1521/AUTOMTN
CDRUSER=hadoop_mercury
CDRPWD=XU91abLt10aDMb
CDRSPLITBY=FILE_ID

FASTTRACKCONNECT=jdbc:oracle:thin:@som-racload03.humedica.net:1521/AUTOMTN
FASTTRACKUSER=fasttrack
FASTTRACKPWD=Fs9056azePRN1zcwq05
FASTTRACKSPLITBY=FILE_ID


#SCHEMA=$1
DEST=RXORDER_TABLES_20171125


./acquireRxOrderTable.sh  AS_ERX H984926_AS_MISAG_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H984926_AS_MISAG_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H984926_AS_MISAG_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY

./acquireRxOrderTable.sh  AS_ERX H178829_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H178829_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H178829_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY

./acquireRxOrderTable.sh  AS_ERX H285893_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H285893_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H285893_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY

./acquireRxOrderTable.sh  AS_ERX H053731_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H053731_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H053731_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY

./acquireRxOrderTable.sh  AS_ERX H969222_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H969222_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H969222_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY

./acquireRxOrderTable.sh  AS_ERX H973241_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H973241_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H973241_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY


./acquireRxOrderTable.sh  AS_ERX H523461_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H523461_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H523461_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY


./acquireRxOrderTable.sh  AS_ERX H984926_AS_V1  $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H984926_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H984926_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY


./acquireRxOrderTable.sh  AS_ERX H319046_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_ZC_MEDICATION_DE H319046_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY
./acquireRxOrderTable.sh  AS_PATDEM H319046_AS_V1 $DEST $CDRCONNECT $CDRUSER $CDRPWD $CDRSPLITBY

#H984926_AS_MISAG_V1
#H178829_AS_V1
#H285893_AS_V1
#H053731_AS_V1
#H969222_AS_V1
#H973241_AS_V1
#H523461_AS_V1
#H984926_AS_V1
#H319046_AS_V1

